### ISSUE TITLE
Integrate Disqus

### ISSUE THREAD

**Issue by tboerger** [go-gitea/theme#11]
We should integrate Disqus at the footer so that we can get comments on various places.

**Comment by metalmatze** [comment]
hm. I thought we wouldn't have that, because it spreads all comments and requests all over the place. Gitter is faster to ask anyway. I don't think that's a good idea except from the blog maybe...

**Comment by lunny** [comment]
Integrating Disqus on blog and docs is good. Docs and blog are searchable. User can post questions below the content. And it's no need to find gitter entry and sign in to chat.

**Comment by tboerger** [comment]
Solved via https://github.com/go-gitea/theme/pull/14
