### ISSUE TITLE
Problem with docs stylesheet on gitea.io

### ISSUE THREAD

**Issue by jmn** [go-gitea/theme#31]
Tested on Chrome/Chromium

![image](https://cloud.githubusercontent.com/assets/35616/22281900/a6640a0a-e2d9-11e6-814a-23ecc91972ac.png)

e.g. https://docs.gitea.io/en-us/install-from-package/

**Comment by tboerger** [comment]
@metalmatze I'm pretty sure this is related to the new box model of a more current beta for bootstrap :(

**Comment by metalmatze** [comment]
That's probably right. I can try debugging this later.

**Comment by tboerger** [comment]
Will be solved via https://github.com/go-gitea/theme/pull/32
