### ISSUE TITLE
New "more modern" theme

### ISSUE THREAD

**Issue by kolaente** [go-gitea/theme#52]
I'd love to update the Gitea website theme into something more modern like this:
![bildschirmfoto vom 2018-04-14 um 13 12 16](https://user-images.githubusercontent.com/13721712/38767648-7a47bccc-3fe5-11e8-8d27-d8f7fba29667.png)

Any ideas/thoughts/comments/opinions?

**Comment by lunny** [comment]
seems better than current one. and where is the logo?

**Comment by kolaente** [comment]
I'd put that probably in the top left corner.

**Comment by lafriks** [comment]
We could use this bulma template: https://jenil.github.io/bulmaswatch/flatly/

**Comment by kolaente** [comment]
@lafriks looks good

**Comment by daviian** [comment]
@kolaente Guess this is resolved now :smiley: :tada:
